[[allowlists]]
  description = "Allow specific secret files as they are not secrets that matter."

  paths = [
    "components/apps/users/files/users.htpasswd",
    "components/apps/users/base/htpass-secret.yaml",
    "components/apps/keycloak/base/admin-secret.yaml",
    "components/platform/oauth/yaml/oauth-secret.yaml"
  ]
