apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: user1
groups: null
identities:
- local-htpasswd:user1

--- 

apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: user2
groups: null
identities:
- local-htpasswd:user2

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-free-users
users: [bryonbaker]

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-premium-users
users: [user1]

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-enterprise-users
users: []

---

# Define groups for developers in Acme Inc

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: acme-dev-users
users: [bryonbaker]

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: acme-prod-users
users: [bryonbaker, user2]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-user-view-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: user1
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: user2

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-config-viewer
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-config-viewer-user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-config-viewer
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: user1
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: user2
