apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-metering-2-sa
  namespace: maas-metering-2
  labels:
    app: maas-metering-2
    app.kubernetes.io/name: maas-metering-2
    app.kubernetes.io/part-of: models-as-a-service

