apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: sno-jp2zl-4xlarge-worker-us-east-2c
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: sno-jp2zl
spec:
# Do not hard code this so Argo does not overwrite it when you scale manually
#  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: sno-jp2zl
      machine.openshift.io/cluster-api-machineset: sno-jp2zl-4xlarge-worker-us-east-2c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: sno-jp2zl
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: sno-jp2zl-4xlarge-worker-us-east-2c
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          credentialsSecret:
            name: aws-cloud-credentials
          capacityReservationId: ''
          instanceType: m6i.4xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 120
                volumeType: gp3
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - sno-jp2zl-node
            - filters:
                - name: 'tag:Name'
                  values:
                    - sno-jp2zl-lb
          kind: AWSMachineProviderConfig
          metadataServiceOptions: {}
          tags:
            - name: kubernetes.io/cluster/sno-jp2zl
              value: owned
          deviceIndex: 0
          ami:
            id: ami-0bc8dda494f111572
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - sno-jp2zl-subnet-private-us-east-2c
          apiVersion: machine.openshift.io/v1beta1
          iamInstanceProfile:
            id: sno-jp2zl-worker-profile