apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instances-health-check
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: "38"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/maas-experiments'
    targetRevision: main
    path: components/platform/instances-health-check/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  revisionHistoryLimit: 5

