apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lws-instance
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Wave 36: Leader Worker Set instance (before instances health check gate)
    argocd.argoproj.io/sync-wave: "36"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/maas-experiments'
    targetRevision: main
    path: components/platform/lws-instance/base
  destination:
    server: https://kubernetes.default.svc
    namespace: leader-worker-set
  syncPolicy:
    automated:
      enabled: true       # Enables automated sync
      prune: true         # Auto-prune deleted resources
      selfHeal: true      # Auto-correct manual cluster changes
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true  # Skip if CRD not ready yet
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  revisionHistoryLimit: 5
