apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpai-default-dsc
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Wave 42: OCPAI DataScienceCluster instance (after instances health check gate at wave 38)
    argocd.argoproj.io/sync-wave: "42"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/maas-experiments'
    targetRevision: main
    path: components/platform/ocpai/base
  destination:
    server: https://kubernetes.default.svc
    # namespace: redhat-ods-operator   # This is cluster scoped
  syncPolicy:
    automated:
      enabled: true       # Enables automated sync
      prune: true         # Auto-prune deleted resources
      selfHeal: true      # Auto-correct manual cluster changes
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true  # Skip if CRD not ready yet
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  revisionHistoryLimit: 5
