apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpai-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Wave 18: OpenShift AI operator (LAST - depends on kueue, nvidia, lws)
    argocd.argoproj.io/sync-wave: "18"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/maas-experiments'
    targetRevision: main
    path: components/operators/ocpai_3_0/base
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-operator
  syncPolicy:
    # Auto sync - changes will automatically sync from Git
    automated:
      enabled: true       # Enables automated sync
      prune: true         # Auto-prune deleted resources
      selfHeal: true      # Auto-correct manual cluster changes
    syncOptions:
      - CreateNamespace=true
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
