apiVersion: v1
kind: Service
metadata:
  name: maas-metering
  namespace: maas-metering
  labels:
    app: maas-metering
    app.kubernetes.io/name: maas-metering
    app.kubernetes.io/component: metering
    app.kubernetes.io/part-of: models-as-a-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: maas-metering

