apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-metering-sa
  namespace: maas-metering
  labels:
    app: maas-metering
    app.kubernetes.io/name: maas-metering
    app.kubernetes.io/part-of: models-as-a-service

