apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - github:
      clientID: Ov23liCRdg5K5jlfAoSd
      clientSecret:
        name: github-oauth-secret
      organizations:
      - ExternalOpenShiftAuthz
    mappingMethod: claim
    name: github
    type: GitHub
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: local-htpasswd
    type: HTPasswd

