apiVersion: v1
kind: Secret
data:
  htpasswd: YWNtZS11c2VyMTokMnkkMDUkME5GMGJuQ09rN1dpNDdIeTV3RHRELkw5Ni5PbWN2T0xCZmg5c280YUYyQjkzalQubWpOUFMKYWNtZS11c2VyMjokMnkkMDUkOEFPeWZzWnZYZ0NTSXhZTXNHdUt5T3hzd1pHREw4akFHZ2VpcWlET1FibUlBemZmbHo4Tk8K
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
